feat(auth): Implement social authentication
andela/neon-ah-frontend pull request #13
Opened 2019-02-12 11:13 UTC by jesseinit

#### What does this PR do?
- Implement a feature which enables authentication using their social account (Twitter, Google, LinkedIn, and Facebook)

#### Description of Task to be completed?
- Setup auth reducer
- Write tests
- Design login Modal
- Define social authentication routes
- Setup custom error me

#### How should this be manually tested?
- Clone the repo
- Install dependencies with `npm install`
- Test with `npm t`

#### What are the relevant pivotal tracker stories?
[Implement social authentication](https://www.pivotaltracker.com/story/show/162414232)

2019-02-12 11:18 UTC, Makwe-O commented
LGTM, Yet

2019-02-12 15:30 UTC, rafmme commented on src/reducer/authReducer/authReducer.test.js
> +  /* localStorage.setItem(
Commented line here

2019-02-13 09:57 UTC, profmcdan requested changes
Kindly come up with a design that helps to manage Facebook Users who registered with their phone number.

2019-02-15 11:09 UTC, seunkoko approved these changes

2019-02-15 11:10 UTC, merged